# Generated by Django 3.1.7 on 2021-04-04 00:41

import accounts.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=140, unique=True, verbose_name='email')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=14, verbose_name='Contato')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=140, verbose_name='Sobrenome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário ativo')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.image')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created'],
            },
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
    ]
