# Generated by Django 3.1.7 on 2021-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_high_url', models.ImageField(upload_to='images', verbose_name='Image (high)')),
                ('image_medium_url', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image (medium)')),
                ('image_low_url', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image (low)')),
            ],
        ),
    ]
